# Generated by Django 4.2.1 on 2023-05-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_livros_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
    ]
