# Generated by Django 4.2.1 on 2023-05-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0005_remove_livros_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='nome_emprestado',
            new_name='nome_emprestado_sem_cadastro',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='nome_emprestado_com_cadastro',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
