# Generated by Django 4.2.1 on 2023-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_remove_emprestimo_tempo_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='livros',
            name='co_autor',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
