# Generated by Django 4.2.1 on 2023-05-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_rename_nome_emprestado_com_cadastro_emprestimo_nome_cadastrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='nome',
            field=models.CharField(max_length=45),
        ),
    ]
